ClientCardManager.Presentation.WebApp/Controllers/ClienteTarjetaController.cs
using CientCardManager.Core.Application.Interfaces.Servicios;
using CientCardManager.Core.Application.ViewModels.Cliente;
using CientCardManager.Core.Application.ViewModels.ClienteTarjeta;
using CientCardManager.Core.Application.ViewModels.TipoTarjeta;
using ClientCardManager.Core.Domain.Entidad;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Text.RegularExpressions;

namespace ClientCardManager.Presentation.WebApp.Controllers
{
    public class ClienteTarjetaController : Controller
    {
        private readonly IServicioGenerico<SaveClienteTarjetaVM, ClienteTarjetaVM, ClienteTarjeta> _service;
        private readonly IServicioGenerico<SaveTipoTarjetaVM, TipoTarjetaVM, TipoTarjeta> _serviceTipoTarjeta;
        private readonly IServicioGenerico<SaveClienteVM, ClienteVM, Cliente> _serviceCliente;

        public ClienteTarjetaController(IServicioGenerico<SaveClienteTarjetaVM, ClienteTarjetaVM, ClienteTarjeta> service, IServicioGenerico<SaveTipoTarjetaVM, 
            TipoTarjetaVM, TipoTarjeta> serviceTipoTarjeta, IServicioGenerico<SaveClienteVM, ClienteVM, Cliente> serviceCliente)
        {
            _service = service;
            _serviceTipoTarjeta = serviceTipoTarjeta;
            _serviceCliente = serviceCliente;
        }
        public async Task<IActionResult> Index(int id = 0)
        {
            List<ClienteVM> cliente = new List<ClienteVM>()
            {
                new ClienteVM {
                    Id = 0,
                    Nombre = "Selecciona un cliente",
                    Apellido = ""
                }
            };

           cliente.AddRange(await _serviceCliente.GetAll());

            ViewBag.Clientes  = new SelectList(cliente.Select(S => new {
                value = S.Id,
                name = $"{S.Nombre} {S.Apellido}"
            }), "value", "name");
           
            return View(new ClienteTarjetaVM() { IdCliente = id});
            
        }
        [HttpGet]
        public async Task<IActionResult> Crear(int id)
        {
            var tiposTarjetas = await _serviceTipoTarjeta.GetAll();
            ViewBag.TipoTarjeta = new SelectList(tiposTarjetas.Select(S => new {
                value = S.Id,
                name = S.Nombre
            }), "value", "name");

            var response = await _serviceCliente.GetById(id);

            return View("Save", new SaveClienteTarjetaVM() { 
                NombreCliente = $"{response.Nombre} {response.Apellido}",
                MesVencimiento = DateTime.Now.AddMonths(1).Month,
                AnioVencimiento = DateTime.Now.AddMonths(1).Year,
                IdCliente = id
            });
        }
        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            var tiposTarjetas = await _serviceTipoTarjeta.GetAll();
            ViewBag.TipoTarjeta = new SelectList(tiposTarjetas.Select(S => new {
                value = S.Id,
                name = S.Nombre
            }), "value", "name");

            var response = await _service.GetById(id,x=>x.Cliente);

            var sv = _service.MapepVmToSv(response);
            sv.NombreCliente = $"{response.Cliente.Nombre} {response.Cliente.Apellido}";            

            return View("Save",  sv);
        }

        [HttpPost]
        public async Task<JsonResult> Crear(SaveClienteTarjetaVM request)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    var errorList = ModelState.Where(x => x.Value.Errors.Any())
                                                 .Select(x => new
                                                 {
                                                     PropertyName = x.Key,
                                                     ErrorMessage = x.Value.Errors.First().ErrorMessage
                                                 })
                                                 .ToList();

                    if (errorList.Any())
                    {
                        var firstError = errorList.First();
                        var propertyName = firstError.PropertyName;
                        var errorMessage = firstError.ErrorMessage;

                        if (propertyName != "FechaHasta")
                        {
                            var error = new
                            {
                                ok = false,
                                titulo = $"El campo {propertyName} es invalido",
                                msj = errorMessage,
                                idCliente = request.IdCliente
                            };
                            return Json(error);
                        }
                    }
                }

                if (string.IsNullOrWhiteSpace(request.Banco))
                {
                    var error = new
                    {
                        ok = false,
                        titulo = "Error banco esta vacio.",
                        msj = "El campo banco no es válido.",
                        idCliente = request.IdCliente
                    };

                    return Json(error);
                }

                if (request.Banco.Count() > 30)
                {
                    var error = new
                    {
                        ok = false,
                        titulo = "Error campo Banco",
                        msj = "El campo Banco es demasiado largo.",
                        idCliente = request.IdCliente
                    };

                    return Json(error);
                }

                if (string.IsNullOrWhiteSpace(request.Numero))
                {
                    var error = new
                    {
                        ok = false,
                        titulo = "Error número esta vacio.",
                        msj = "El campo número no es válido.",
                        idCliente = request.IdCliente
                    };

                    return Json(error);
                }

                request.Banco = request.Banco.ToUpper();

                if (!Regex.IsMatch(request.Numero, @"^\d{4}-\d{4}-\d{4}-\d{4}$"))
                {
                    var error = new
                    {
                        ok = false,
                        titulo = "Error Número de tarjeta.",
                        msj = "Este número de tarjeta no es válido.",
                        idCliente = request.IdCliente
                    };

                    return Json(error);
                }

                if (request.AnioVencimiento < DateTime.Now.Year)
                {
                    var error = new
                    {
                        ok = false,
                        titulo = "Error Fecha Vencimiento.",
                        msj = "Esta fecha ya expiro",
                        idCliente = request.IdCliente
                    };

                    return Json(error);
                }

                if (request.MesVencimiento > 12 || request.MesVencimiento <= 0 || (request.MesVencimiento <= DateTime.Now.Month && request.AnioVencimiento == DateTime.Now.Year))
                {
                    var error = new
                    {
                        ok = false,
                        titulo = "Error Fecha Vencimiento.",
                        msj = "Esta fecha ya expiro",
                        idCliente = request.IdCliente
                    };

                    return Json(error);
                }


                if (await _service.Exists(x=>x.Numero == request.Numero))
                {
                    var error = new
                    {
                        ok = false,
                        titulo = "Número de tarjeta ya existe.",
                        msj = "Este número de tarjeta ya existe.",
                        idCliente = request.IdCliente
                    };

                    return Json(error);
                }

                if (!await _serviceCliente.Exists(x => x.Id == request.IdCliente))
                {
                    var error = new
                    {
                        ok = false,
                        titulo = "Error este cliente no existe",
                        msj = "El cliente es inválido.",
                        idCliente = request.IdCliente

                    };

                    return Json(error);
                }

                if (!await _serviceTipoTarjeta.Exists(x => x.Id == request.IdTipoTarjeta))
                {
                    var error = new
                    {
                        ok = false,
                        titulo = "Error este tipo de tarjeta no existe",
                        msj = "Tipo tarjeta es inválido.",
                        idCliente = request.IdCliente

                    };

                    return Json(error);
                }

                if (await _serviceCliente.Exists(x => x.Id == request.Id && x.Activo == false))
                {
                    var error = new
                    {
                        ok = false,
                        titulo = "Error este cliente esta incativo",
                        msj = "El cliente no puede ser actualizado, mientra este inactivo.",
                        idCliente = request.IdCliente
                    };

                    return Json(error);
                }

                bool result = await _service.Add(request);

                if (!result)
                {
                    var error = new
                    {
                        ok = false,
                        titulo = "Error del servidor",
                        msj = "Por favor, ponerse en contacto con soporte tecnico.",
                        idCliente = request.IdCliente
                    };

                    return Json(error);
                }

                var response = new

ClientCardManager.Presentation.WebApp/Views/ClienteTarjeta/Index.cshtml
@model CientCardManager.Core.Application.ViewModels.ClienteTarjeta.ClienteTarjetaVM;
@{
    ViewData["Title"] = "Asociación Tarjetas";
}
<div id="container" class="container-fluid mt-md-5">    
    
    <table id="tablaClienteTarjeta" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0">
        <thead class="main-table">
            <tr>
                <th>Cliente</th>
                <th>Tipo Tarjeta</th>
                <th>Número de Tarjeta</th>
                <th>Banco</th>
                <th>Acciones</th>
            </tr>
        </thead>

    </table>
</div>
<div class="col-md-3 TopDivTable">
    <a id="btnCrear" type="button" class="btn btn-success"><i class="fa-regular fa-id-card"></i> Asociar Tarjeta</a>
</div>

<div class="col-md-3 mt-2 TopMidDivTable">
    <select id="selectCliente" class="form-control select2 selectCliente" asp-items="ViewBag.Clientes" asp-for="IdCliente">
        
    </select>
</div>
<div id="modalClienteTarjeta">

</div>


@section Scripts {
   <script src="~/js/ClienteTarjeta/Index.js"></script>
}

ClientCardManager.Presentation.WebApp/Views/ClienteTarjeta/Save.cshtml
@model CientCardManager.Core.Application.ViewModels.ClienteTarjeta.SaveClienteTarjetaVM;

@{
    Layout = null;
    bool editMode = Model.Id != 0;
}

<div class="modal fade clienteTarjetaModal" id="ClienteTarjetaModal" tabindex="-1" role="dialog" aria-labelledby="ClienteTarjetaModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="crearClienteTarjetaModalLabel">@(editMode ? "Editar" : "Nueva") Tarjeta <i class="fa-regular fa-id-card"></i></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>                
            </div>
            <form class="formClienteTarjeta" method="post" asp-action="@(editMode? "Editar":"Crear")" asp-controller="ClienteTarjeta">
                <div class="modal-body">
                    <div class="container">
                            <input hidden id="txtId" asp-for="Id" type="number" value="@Model.Id" />
                            <div class="row justify-content-start">
                                <div class="col-12">
                                    <div class="mb-3">
                                        <label class="form-label" for="txtNombre">Cliente</label>
                                        <input readonly asp-for="NombreCliente" class="form-control" style="background-color:lightgray" value="@Model.NombreCliente" />
                                        <input hidden type="number" class="form-control" id="txtNombre" asp-for="IdCliente" value="@Model.IdCliente">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="mb-3">
                                        <label class="form-label" for="txtNombre">Banco</label>                                        
                                        <input placeholder="Banco de Reservas" type="text" class="form-control" id="txtBanco" asp-for="Banco" value="@Model.Banco">
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="mb-3">
                                        <label class="form-label" for="selectTarjeta">Tipo de Tarjeta</label>
                                    <select class="select2 form-control selectTarjeta select2" asp-for="IdTipoTarjeta" asp-items="ViewBag.TipoTarjeta"></select>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="mb-3">
                                    <label class="form-label" for="txtNumero">Número de Tarjeta</label>
                                    <input placeholder="0000-0000-0000-0000" type="text" class="form-control numero-tarjeta" id="txtNumero" asp-for="Numero" value="@Model.Numero">
                                    </div>
                                </div>
                                <div class="col-3">
                                    <div class="mb-3">
                                        <label class="form-label" for="txtAnioVencimiento">Año</label>                                        
                                        <input min="1901" type="number" class="form-control" id="txtAnioVencimiento" asp-for="AnioVencimiento" value="@Model.AnioVencimiento">
                                    </div>
                                </div>
                                <div class="col-3">
                                    <div class="mb-3">
                                    <label class="form-label" for="txtMesVencimiento">Mes</label>
                                    <input type="number" min="1" max="12" class="form-control" id="txtMesVencimiento" asp-for="MesVencimiento" value="@Model.MesVencimiento">
                                 </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="fa-solid fa-xmark"></i> Cancelar</button>
                    <button type="submit" class="btn btn-primary ">
                        <i class="fa-solid fa-check"></i>
                         @(editMode ? "Actualizar" : "Agregar")                        
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="~/js/ClienteTarjeta/Save.js"></script>