ClientCardManager.Presentation.WebApp/Controllers/TipoTarjetaController.cs
using CientCardManager.Core.Application.Interfaces.Servicios;
using CientCardManager.Core.Application.ViewModels.TipoTarjeta;
using ClientCardManager.Core.Domain.Entidad;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ClientCardManager.Presentation.WebApp.Controllers
{
    public class TipoTarjetaController : Controller
    {
        private readonly IServicioGenerico<SaveTipoTarjetaVM, TipoTarjetaVM, TipoTarjeta> _service;
        public TipoTarjetaController(IServicioGenerico<SaveTipoTarjetaVM, TipoTarjetaVM, TipoTarjeta> service)
        {
            _service = service;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Crear()
        {
            return View("Save", new SaveTipoTarjetaVM());
        }
        [HttpGet]
        public async Task<IActionResult> Editar(int id)
        {
            var response = await _service.GetByIdSv(id);
            return View("Save", response);
        }
        [HttpPost]
        public async Task<JsonResult> Crear(SaveTipoTarjetaVM request)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    var errorList = ModelState.Where(x => x.Value.Errors.Any())
                                                 .Select(x => new
                                                 {
                                                     PropertyName = x.Key,
                                                     ErrorMessage = x.Value.Errors.First().ErrorMessage
                                                 })
                                                 .ToList();

                    if (errorList.Any())
                    {
                        var firstError = errorList.First();
                        var propertyName = firstError.PropertyName;
                        var errorMessage = firstError.ErrorMessage;

                        if (propertyName != "FechaHasta")
                        {
                            var error = new
                            {
                                ok = false,
                                titulo = $"El campo {propertyName} es invalido",
                                msj = errorMessage
                            };
                            return Json(error);
                        }
                    }
                }

                if (string.IsNullOrWhiteSpace(request.Nombre))
                {
                    var error = new
                    {
                        ok = false,
                        titulo = "Campo invalido",
                        msj = "El campo Nombre es invalido",
                    };

                    return Json(error);
                }

                if (request.Nombre.Count() > 30)
                {
                    var error = new
                    {
                        ok = false,
                        titulo = "Error campo Nombre",
                        msj = "El campo Nombre es demasiado largo.",
                    };

                    return Json(error);
                }

                request.Nombre = request.Nombre.ToUpper();

                bool result = await _service.Add(request);

                if (!result)
                {
                    var error = new
                    {
                        ok = false,
                        titulo = "Error del servidor",
                        msj = "Por favor, ponerse en contacto con soporte tecnico.",
                    };

                    return Json(error);
                }

                var response = new
                {
                    ok = true,
                    titulo = "Correcto!!",
                    msj = "Todo ha salido correcto.",
                };

                return Json(response);
            }
            catch (Exception ex)
            {
                var error = new
                {
                    ok = false,
                    titulo = "Error del servidor",
                    msj = $"{ex.InnerException.Message}",
                };

                return Json(error);
            }
        }

        [HttpPost]
        public async Task<JsonResult> Editar(SaveTipoTarjetaVM request)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    var errorList = ModelState.Where(x => x.Value.Errors.Any())
                                                 .Select(x => new
                                                 {
                                                     PropertyName = x.Key,
                                                     ErrorMessage = x.Value.Errors.First().ErrorMessage
                                                 })
                                                 .ToList();

                    if (errorList.Any())
                    {
                        var firstError = errorList.First();
                        var propertyName = firstError.PropertyName;
                        var errorMessage = firstError.ErrorMessage;

                        if (propertyName != "FechaHasta")
                        {
                            var error = new
                            {
                                ok = false,
                                titulo = $"El campo {propertyName} es invalido",
                                msj = errorMessage
                            };
                            return Json(error);
                        }
                    }
                }


                if (string.IsNullOrWhiteSpace(request.Nombre))
                {
                    var error = new
                    {
                        ok = false,
                        titulo = "Campo invalido",
                        msj = "El campo Nombre es invalido",
                    };

                    return Json(error);
                }

                if (request.Nombre.Count() > 30)
                {
                    var error = new
                    {
                        ok = false,
                        titulo = "Error campo Nombre",
                        msj = "El campo Nombre es demasiado largo.",
                    };

                    return Json(error);
                }

                request.Nombre = request.Nombre.ToUpper();

                if (!await _service.Exists(x => x.Id == request.Id))
                {
                    var error = new
                    {
                        ok = false,
                        titulo = "Error esta tipo tarjeta no existe",
                        msj = "Tipo de tarjeta es inválido.",
                    };

                    return Json(error);
                }

                bool result = await _service.Update(request);

                if (!result)
                {
                    var error = new
                    {
                        ok = false,
                        titulo = "Error del servidor",
                        msj = "Por favor, ponerse en contacto con soporte tecnico.",
                    };

                    return Json(error);
                }

                var response = new
                {
                    ok = true,
                    titulo = "Correcto!!",
                    msj = "Todo ha salido correcto.",
                };

                return Json(response);
            }
            catch (Exception ex)
            {
                var error = new
                {
                    ok = false,
                    titulo = "Error del servidor",
                    msj = $"{ex.InnerException.Message}",
                };

                return Json(error);
            }
        }
        public async Task<JsonResult> ObtenerTipoTarjetas()
        {
            var result = await _service.GetList(null, x => x.Include(y => y.Tarjetas));

            var response = result.Select(x => new
            {
                x.Id,
                x.Nombre,
                ultimaModificacion = x.UltimaModificacion.HasValue ? x.UltimaModificacion.Value.ToString("dd/MM/yyy") : x.Creado.ToString("dd/MM/yyy"),
                tarjetas = x.Tarjetas.Count(),                
            }).ToList();

            return Json(new { data = response });
        }
    }
}

ClientCardManager.Presentation.WebApp/Views/TipoTarjeta/Index.cshtml
@{
    ViewData["Title"] = "Tipo Tarjeta";
}
<div class="container-fluid mt-md-5">
    <div id="TopDivTable" class="col-md-6">
        <a id="btnCrear" type="button" class="btn btn-success"><i class="fa-solid fa-credit-card"></i> Nueva Tarjeta</a>
    </div>
    <table id="tablaTipoTarjeta" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0">
        <thead class="main-table">
            <tr>
                <th>#</th>
                <th>Nombre</th>
                <th>Tarjetas</th>
                <th>Último Registro</th>
                <th>Acciones</th>
            </tr>
        </thead>

    </table>
</div>

<div id="modalTarjeta">

</div>


@section Scripts {
   <script src="~/js/TipoTarjeta/Index.js"></script>
}

ClientCardManager.Presentation.WebApp/Views/TipoTarjeta/Save.cshtml
@model CientCardManager.Core.Application.ViewModels.TipoTarjeta.SaveTipoTarjetaVM;

@{
    Layout = null;
    bool editMode = Model.Id != 0;
}

<div class="modal fade" id="TipoTarjetaModal" tabindex="-1" role="dialog" aria-labelledby="TipoTarjetaModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="crearTipoTarjetaModalLabel">@(editMode ? "Editar" : "Nueva") Tipo Tarjeta <i class="fa-solid fa-credit-card"></i></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>                
            </div>
            <form class="formTipoTarjeta" method="post" asp-action="@(editMode? "Editar":"Crear")" asp-controller="TipoTarjeta">
                <div class="modal-body">
                    <div class="container">
                            <input hidden id="txtId" asp-for="Id" type="number" value="@Model.Id" />
                            <div class="row justify-content-start">
                                <div class="col-12">
                                    <div class="mb-3">
                                        <label class="form-label" for="txtNombre">Nombre</label>
                                        <input placeholder="debito" type="text" class="form-control" id="txtNombre" asp-for="Nombre" value="@Model.Nombre">
                                    </div>
                                </div>                               
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="fa-solid fa-xmark"></i> Cancelar</button>
                    <button type="submit" class="btn btn-primary ">
                        <i class="fa-solid fa-check"></i>
                         @(editMode ? "Actualizar" : "Agregar")                        
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="~/js/TipoTarjeta/Save.js"></script>